### ISSUE TITLE
Circle function with missing parameter

### ISSUE THREAD

**Issue by 1337GameDev** [paddy-exe/ShaderFunction-Extras#23]
I noticed this when looking around and tinkering with this package and figured i'd mention it:

`addons/ShaderFunction-Extras/Shapes/shapes.gdshaderinc`

the function "circle" is missing "position" (which appears to be vec3)

<img width="716" alt="Screenshot 2023-12-17 at 4 33 36 PM" src="https://github.com/paddy-exe/ShaderFunction-Extras/assets/5528175/d83fa2c8-25c7-45d5-8276-110ea8958a74">

I'd suggest a signature change to: 

`float circle(vec3 position, vec2 uv, float radius, float feather)`

**Comment by paddy-exe** [comment]
Hey, thanks for reporting this bug! I will get on it👍🏻
